# Generated by Django 4.1.4 on 2023-01-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userfollow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='follows_id',
            new_name='follows',
        ),
    ]
